### PR TITLE
fix: make it noop on non-android platforms

### PR DESCRIPTION
**Pull request by kuasha420**
Currently, calling changeBarColors without platform checks results in error.

Simulator Screen Shot - iPhone 12 - 2021-05-23 at 18 23 11

This will allow you to call changeBarColors without platform checks

### CODE REVIEW

**Comment by crutchcorn** [comment]
LOL. I make sure to have an `index.js` file with the right shape, etc only to have the package point to the wrong file 🤦

Some days my coding mistakes amaze even myself. 

Thanks for the PR. I have one small request before merging but we'll get it merged quickly after

**Comment by kuasha420** [comment]
@crutchcorn haha. At first I thought It's something I put in Babel Config Module Resolver that's screwing up.  :) I found it very funny when I figured out the cause. 

Let me know if anything needs to be done. 

Cheers

**Comment by cam-shaw** [comment]
@crutchcorn any chance we could get this looked at again? We can add a catch around it in the meantime haha

**Comment by crutchcorn** [comment]
Oh, shoot! Thanks for reminding @cam-shaw! My desktop died like the day after this was opened and I've been trying to fix it since, so I got distracted 😅

I have my laptop avail that I'm using right now. 

I'll merge right now and publish tonight. Sorry for the delay y'all!

**Comment by crutchcorn** [comment]
Published via `1.0.3`

**Comment by kuasha420** [comment]
<3

**Pull request merged**
